### PR TITLE
Few CSS modification for better readability and accessibility

### PR DESCRIPTION
**Pull request by webVerts**
Added a default border for input forms.
Changed default pink color for links to a darker shade, for better readability

### CODE REVIEW

**Comment by mrvivacious** [comment]
Woah, thank you for the edit and PR!
I'll check this out later today. Meanwhile, would it be possible for you to upload a screenshot of the new UI? Otherwise I'll check manually later of course.

Thanks again!!

**Comment by webVerts** [comment]
I didn't export it as chrome extension, so currently I only can preview using html previewer


image

BTW @mrvivacious  is it okay if I pull a request with twitter NSFW profiles.

**Comment by mrvivacious** [comment]
Thanks for the PR! :)

**Comment by mrvivacious** [comment]
What do you have in mind for twitter? Plz open a new PR for that so we can keep discussions organized

What are nsfw profiles on twitter? I dont use twitter much but open to checking out with u

**Comment by mrvivacious** [comment]
I like the border around the inputs, makes it clearer that those are input fields and not just text. Good thinking.

**Pull request merged**
